# Multi-stage Dockerfile for building and serving a Vite static site

# 1) Build stage
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies first (leverage Docker layer cache)
COPY package*.json ./
RUN npm ci

# Copy the rest of the source and build
COPY . .
RUN npm run build

# 2) Runtime stage using Nginx to serve static files
FROM nginx:1.25-alpine AS runner

# Remove default config and add SPA-friendly config (fallback to /index.html)
RUN rm -f /etc/nginx/conf.d/default.conf \
  && printf "server {\n  listen 80;\n  server_name _;\n  root /usr/share/nginx/html;\n  index index.html;\n\n  location / {\n    try_files $$uri /index.html;\n  }\n\n  # Cache immutable assets generated by Vite\n  location /assets/ {\n    expires 1y;\n    add_header Cache-Control \"public, immutable\";\n  }\n}\n" > /etc/nginx/conf.d/default.conf

# Copy build artifacts
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]